package com.test;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;

public class automation {
public static void main(String[] args) throws InterruptedException {
	System.setProperty("webdriver.chrome.driver","C:\\Users\\Kanagalatha\\eclipse-workspace\\java-5pm\\Selenium_Projects\\driverC\\chromedriver.exe" );
	WebDriver driver=new ChromeDriver();
	driver.get("http://automationpractice.com/index.php");
	driver.manage().window().maximize();
	WebElement women = driver.findElement(By.xpath("//a[@title=\"Women\"]"));
    Actions s = new Actions(driver);
    s.moveToElement(women).build().perform();
    WebElement dresses = driver.findElement(By.xpath("(//a[@title='Dresses'])[2]"));
    dresses.click();
    Thread.sleep(3000);
   // WebElement casual = driver.findElement(By.xpath("//a[contains(@ti,'You are looking')]"));
   // casual.click();
   // Thread.sleep(3000);
  // WebElement instock = driver.findElement(By.xpath("(//span[@class='available-now'])[5]"));
    //s.moveToElement(instock).build().perform();
   // WebElement more = driver.findElement(By.xpath("(//a[@itemprop='url'])[15]"));
   // more.click();
  // JavascriptExecutor js = (JavascriptExecutor)driver;
   //js.executeScript("window.scrollby(0,750)");
  // WebElement cart = driver.findElement(By.xpath("//a[@title='View my shopping cart']"));
   // cart.click();
   // Thread.sleep(3000);
    WebElement casualdress = driver.findElement(By.xpath("(//a[@class='subcategory-name'])[1]"));
    casualdress.click();
    Thread.sleep(3000);
    WebElement instock = driver.findElement(By.xpath("//span[@class='available-now']"));
    Thread.sleep(3000);
    s.moveToElement(instock).build().perform();
    WebElement more = driver.findElement(By.xpath("//a[@class='button lnk_view btn btn-default']"));
    more.click();
    Thread.sleep(3000);
    WebElement quantity = driver.findElement(By.id("quantity_wanted"));
    quantity.sendKeys("9");
    WebElement addtocart = driver.findElement(By.xpath("//span[text()='Add to cart']"));
    addtocart.click();
    Thread.sleep(3000);
    WebElement proceed = driver.findElement(By.xpath("//a[@class='btn btn-default button button-medium']"));
    proceed.click();
    Thread.sleep(3000);
    WebElement checkout = driver.findElement(By.xpath("(//a[@title='Proceed to checkout'])[2]"));
    checkout.click();
    Thread.sleep(3000);
    WebElement email = driver.findElement(By.xpath("(//input[@type='text'])[2]"));
    email.sendKeys("bommu0928@gmail.com");
    WebElement create_account = driver.findElement(By.xpath("(//button[@type='submit'])[2]"));
    create_account.click();
    Thread.sleep(3000);
    WebElement gender = driver.findElement(By.xpath("(//input[@type='radio'])[1]"));
    gender.click();
    WebElement fname = driver.findElement(By.xpath("(//input[@type=\"text\"])[2]"));
    fname.sendKeys("kishore");
    WebElement lname = driver.findElement(By.xpath("(//input[@type=\"text\"])[3]"));
    lname.sendKeys("kizzy");
    WebElement password = driver.findElement(By.xpath("//input[@type=\"password\"]"));
    password.sendKeys("kishore123");
   // WebElement date = driver.findElement(By.xpath("(//div[@class=\"selector\"])[1]"));
   // Select s1 = new Select(date);
    //s1.selectByValue("10");
   // Thread.sleep(3000);
   WebElement day = driver.findElement(By.id("days"));
   Select d = new Select(day);
   d.selectByIndex(16);
   Thread.sleep(3000);
   WebElement month = driver.findElement(By.id("months"));
   Select m = new Select(month);
   m.selectByVisibleText("January ");
   Thread.sleep(3000);
   WebElement year = driver.findElement(By.id("years"));
   Select y = new Select(year);
   y.selectByValue("2016");
   Thread.sleep(3000);
   WebElement news = driver.findElement(By.id("newsletter"));
   news.click();
   WebElement mr = driver.findElement(By.xpath("(//input[@type=\"checkbox\"])[2]"));
   mr.click();
   WebElement company = driver.findElement(By.xpath("(//input[@type=\"text\"])[7]"));
   company.sendKeys("kishore2525");
   WebElement address = driver.findElement(By.xpath("(//input[@type=\"text\"])[8]"));
   address.sendKeys("mahalakshmi avenue ");
   WebElement address1 = driver.findElement(By.xpath("(//input[@type=\"text\"])[9]"));
   address1.sendKeys("valasaravakkam");
   WebElement city = driver.findElement(By.xpath("(//input[@type=\"text\"])[10]"));
   city.sendKeys("chennai");
   WebElement state = driver.findElement(By.id("id_state"));
   Select s1 = new Select(state);
   s1.selectByVisibleText("Alaska");
   WebElement zip = driver.findElement(By.xpath("(//input[@type=\"text\"])[11]"));
   zip.sendKeys("60016");
   //WebElement country = driver.findElement(By.id("id_country"));
   //Select s2 = new Select(country);
  // s2.selectByVisibleText("United States");
   WebElement phoneno = driver.findElement(By.xpath("(//input[@type=\"text\"])[12]"));
   phoneno.sendKeys("123457895");
   WebElement mobile = driver.findElement(By.xpath("(//input[@type=\"text\"])[13]"));
   mobile.sendKeys("989898998");
   WebElement address2 = driver.findElement(By.xpath("(//input[@type=\"text\"])[14]"));
   address2.sendKeys("belgium");
   Thread.sleep(3000);
   WebElement submit = driver.findElement(By.id("submitAccount"));
   submit.click();
  WebElement proceed1 = driver.findElement(By.xpath("(//button[@type=\"submit\"])[2]"));
  proceed1.click(); 
  WebElement agree = driver.findElement(By.id("cgv"));
  agree.click();
  Thread.sleep(3000);
  WebElement checkout1 = driver.findElement(By.xpath("//button[@name=\"processCarrier\"]"));
  checkout1.click(); 
  Thread.sleep(3000);
  WebElement bank = driver.findElement(By.xpath("//a[@class=\"bankwire\"]"));
  bank.click();
  WebElement pay = driver.findElement(By.xpath("//button[@class=\"button btn btn-default button-medium\"]"));
  pay.click();
}
}
